---
title: 'Stat 316: Multiple Linear Regression Review'
subtitle: 'Bank Salary Case Study'
output:
  pdf_document:
    fig_height: 3
    fig_width: 4.5
  html_document: default
  word_document: default
editor_options: 
  chunk_output_type: console
---

```{r, setup, include=FALSE}
library(mosaic)
library(skimr)   # may have to install
library(dplyr)  
library(ggplot2)
library(gridExtra)
setwd("C:/Users/Ann Cannon/Dropbox/College Computer/courses/sta 363/R directory")
bank <- read.csv("data/banksalary.csv")
```

Data from skilled entry-level clerical workers at bank being sued for sex discrimination in 1970s (from Statistical Sleuth, Ch 12):

- `bsal` = beginning salary (annual salary at time of hire)
- `sal77` = annual salary in 1977
- `sex` = MALE or FEMALE
- `senior` = months since hired
- `age` = age in months
- `educ` = years of education
- `exper` = months of prior work experience

```{r}
# Examine data frame
head(bank)       # print first 6 rows

# Generate relevant summary statistics for response variable
favstats(~ bsal, data = bank)

# Look at marginal relationship between sex and beginning salary

# Three options for getting summary statistics
favstats(~ bsal | sex, data = bank)

bank %>%
  group_by(sex) %>%
  summarize(mean = mean(bsal),
            median = median(bsal),
            sd = sd(bsal),
            iqr = IQR(bsal),
            n = n())

# Doesn't seem to render as a pdf
#bank %>%
#  group_by(sex) %>%
#  skim()

# Several options for plotting 1 categorical and 1 numeric variable
boxplot(bsal ~ sex, ylab="Beginning salary", data = bank)
bwplot(sex ~ bsal, data = bank)
ggplot(bank, aes(x = sex, y = bsal)) +
  geom_boxplot() + coord_flip()
ggplot(data = bank, mapping = aes(x = bsal, y = ..density..)) + 
  geom_freqpoly(mapping = aes(colour = sex), binwidth = 250)
ggplot(data = bank, mapping = aes(x = bsal, y = ..density..)) + 
  geom_density(mapping = aes(colour = sex))
ggplot(bank, aes(x=bsal, fill=sex)) +
  geom_density(alpha=0.4)
ggplot(bank, aes(x = sex, y = bsal)) +
  geom_violin() 
ggplot(data = bank) + 
  geom_histogram(mapping = aes(x = bsal)) + 
  facet_wrap(~ sex, nrow = 2)
ggplot(data = bank) + 
  geom_histogram(mapping = aes(x = bsal, y = ..density..)) + 
  facet_wrap(~ sex, nrow = 2)

# Initial analysis of sex vs salary, ignoring other covariates
t.test(bsal ~ sex, data = bank)

model1 = lm(bsal ~ sex, data = bank)
summary(model1)

bank <- bank %>%
  mutate(male = ifelse(sex=="MALE",1,0))   # create our own indicator for sex
t.test(bsal ~ male, var.equal = TRUE, data = bank)

# How are covariates related to response?
ggplot(bank, aes(y = bsal, age)) + 
  geom_point() + 
  geom_smooth(method = lm)
ggplot(bank, aes(y = bsal, exper)) + 
  geom_point() + 
  geom_smooth(method = lm)
ggplot(bank, aes(y = bsal, educ)) + 
  geom_point() + 
  geom_smooth(method = lm)
ggplot(bank, aes(y = bsal, senior)) + 
  geom_point() + 
  geom_smooth(method = lm)

# How are explanatory variables related to each other?
bank0 <- bank %>% select(bsal, age, exper, educ, senior, male)
pairs(bank0)     # matrix of scatterplots 
cor(bank0)       # matrix of correlations

# How are explanatory variables related to sex?
favstats(~ age | sex, data = bank)
ggplot(bank, aes(x = sex, y = age)) +
  geom_boxplot() + coord_flip()

favstats(~ exper | sex, data = bank)
ggplot(bank, aes(x = sex, y = exper)) +
  geom_boxplot() + coord_flip()

favstats(~ educ | sex, data = bank)
ggplot(bank, aes(x = sex, y = educ)) +
  geom_boxplot() + coord_flip()

favstats(~ senior | sex, data = bank)
ggplot(bank, aes(x = sex, y = senior)) +
  geom_boxplot() + coord_flip()

# Fit linear regression with single predictor (education)
model2 = lm(bsal ~ educ, data = bank)
summary(model2)
```

```{r, echo=TRUE, fig.height=10, fig.width=10}
# Residual plots - run off the page unless redo margins
par(mfrow=c(2,2), mar=c(4,4,4,1), oma=c(0.5,0.5,0.5,0))
plot(model2)   # Generate residual diagnostic plots
par(mfrow=c(1,1))
```

```{r}
# Fit multiple regression model with four predictors
model3 = lm(bsal ~ senior + age + educ + exper, data = bank)
summary(model3)
anova(model2, model3, test="F")

# Examine AIC and BIC scores (lower is better)
AIC(model2)                     # AIC-model2
AIC(model3)                     # AIC-model3
AIC(model2, k=log(nrow(bank)))  # BIC-model2
AIC(model3, k=log(nrow(bank)))  # BIC-model3

# Fit linear regression with experience
model4 = lm(bsal ~ exper, data = bank)
summary(model4)
```

```{r, echo=TRUE, fig.height=10, fig.width=10}
# Residual plots - run off the page unless redo margins
par(mfrow=c(2,2), mar=c(4,4,4,1), oma=c(0.5,0.5,0.5,0))
plot(model4)   # Generate residual diagnostic plots
par(mfrow=c(1,1))
```

```{r}
bank <- bank %>%
  mutate(exper2 = exper^2)
model5 = lm(bsal ~ exper + exper2, data = bank)
summary(model5)
```

```{r, echo=TRUE, fig.height=10, fig.width=10}
# Residual plots - run off the page unless redo margins
par(mfrow=c(2,2), mar=c(4,4,4,1), oma=c(0.5,0.5,0.5,0))
plot(model5)   # Generate residual diagnostic plots
par(mfrow=c(1,1))
```

```{r}
# One potential final model
model6 = lm(bsal ~ senior + educ + exper + male, data = bank)
summary(model6)

# Construct 95% CIs for model coefficients the hard way...
betas = summary(model6)$coef[,1]   # store model betas
SEs = summary(model6)$coef[,2]    # store SEs of betas
tstar = qt(.975,model6$df)
lb = betas - tstar*SEs
ub = betas + tstar*SEs
cbind(lb,ub)

# ... or more simply:
confint(model6)

# Investigate interactions with sex
ggplot(bank, aes(y = bsal, x = age, color = sex)) + 
  geom_point() + 
  geom_smooth(method = lm)
ggplot(bank, aes(y = bsal, x = exper, color = sex)) + 
  geom_point() + 
  geom_smooth(method = lm)
ggplot(bank, aes(y = bsal, x = educ, color = sex)) + 
  geom_point() + 
  geom_smooth(method = lm)
ggplot(bank, aes(y = bsal, x = senior, color = sex)) + 
  geom_point() + 
  geom_smooth(method = lm)

# Examine interaction between sex and education
model7 = lm(bsal ~ educ + male + educ:male, data = bank)
summary(model7)


# Should beginning salary be log transformed?
bank <- bank %>% 
  mutate(logbsal = log(bsal))
hist1 <- ggplot(bank, aes(bsal)) + geom_histogram(bins = 10)
hist2 <- ggplot(bank, aes(logbsal)) + geom_histogram(bins = 10)
grid.arrange(hist1, hist2, ncol=2)

# Look at marginal relationship between sex and beginning salary
model6a = lm(logbsal ~ senior + educ + exper + male, data = bank)
summary(model6a)
```

```{r, echo=TRUE, fig.height=10, fig.width=10}
# Residual plots - run off the page unless redo margins
par(mfrow=c(2,2), mar=c(4,4,4,1), oma=c(0.5,0.5,0.5,0))
plot(model6a)   # Generate residual diagnostic plots
par(mfrow=c(1,1))
```

```{r}
# Bonus code: to help with HW1 when looking at 2 categorical variables
ytable <- tally(~ sex + educ, data = bank)
ytable
mosaicplot(ytable, color = c("blue", "light blue"))
prop.table(ytable, 1)

# Other ways to visualize two categorical variables
bank <- bank %>%
  mutate(education = ifelse(educ < 12, "No high school", "High school"),
         education = ifelse(educ > 12, "Some college", education))
ggplot(data = bank) + 
  geom_bar(mapping = aes(x = sex, fill = education)) 
ggplot(data = bank) + 
  geom_bar(mapping = aes(x = sex, fill = education), position = "fill") 
library(ggmosaic)  # need to have ggmosaic package installed
ggplot(data = bank) +
   geom_mosaic(aes(x = product(education, sex), fill=education), na.rm = TRUE)

# Other ways to summarize relationship between two categorical variables
bank %>%
  group_by(sex, education) %>%
  summarise (n = n()) %>%
  mutate(freq = n / sum(n))
```
