---
title: 'Stat 316: Likelihoods'
subtitle: 'Case Study: Does sex run in families?'
output:
  pdf_document:
    fig_height: 3
    fig_width: 4.5
html_document: default
word_document: default
editor_options: 
  chunk_output_type: console
---
  
```{r, setup, include=FALSE}
library(tidyverse)
```

### Model 1: Sex Unconditional Model

Assumes the sex for each birth is independent of other births

```{r}
# Evaluate small set of possible values of pb
pb <- c(.3, .35, .375, .4, .45)  # possible values for prob a boy is born
lik <- pb^3 * (1 - pb)^5         # likelihood of getting observed data
cbind(pb, lik)                   # print table of results
plot(pb, lik, xlab = "possible values of pb", ylab = "Likelihood")
max(lik)                         # maximum likelihood over 5 values of pb
pb[lik == max(lik)]              # value of pb where likelihood maximized

# Evaluate finer grid of possible values of pb
pb <- seq(0, 1, length = 1001)   # possible values for prob a boy is born
lik <- pb^3 * (1 - pb)^5         # likelihood of getting observed data
plot(pb, lik, xlab = "possible values of pb", ylab = "Likelihood", type = "l")
max(lik)                         # maximum likelihood over 1001 values of pb
pb[lik == max(lik)]              # value of pb where likelihood maximized

loglik <- 3 * log(pb) + 5 * log(1 - pb)      # find log likelihoods
plot(pb, loglik, xlab = "possible values of pb", ylab = "Loglikelihood", 
     type = "l")
max(loglik)                    # maximum loglikelihood over 1001 values of pb
pb[loglik == max(loglik)]      # likelihood and loglikelihood max at same spot
mle_pb_m1_small <- pb[loglik == max(loglik)]
max_logL_m1_small <- max(loglik)

# Create ggplot of likelihood and log-likelihood functions
model1grid <- data.frame(pb = pb, lik1 = lik, loglik1 = loglik)
ggplot(data = model1grid, aes(x = pb, y = lik1)) +
  geom_line() +
  labs(x = "possible values of pb", y = "Likelihood")
ggplot(data = model1grid, aes(x = pb, y = loglik1)) +
  geom_line() +
  labs(x = "possible values of pb", y = "log Likelihood")

```

```{r}
# Apply Model 1 to NLSY data (for families with 3 or fewer children)
pb <- seq(0, 1, length = 10001)   # possible values for prob a boy is born
lik <- pb^5416 * (1 - pb)^5256    # likelihood (too small)
max(lik)
summary(lik)  

# loglikelihood of getting observed data
loglik <- 5416 * log(pb) + 5256 * log(1 - pb)   
plot(pb, loglik, xlab = "possible values of pb", ylab = "Loglikelihood", 
     type = "l")
plot(pb[loglik > (-7500)], loglik[loglik > (-7500)],
  xlab = "possible values of pb", 
  ylab = "Loglikelihood", type = "l")  # zoom plot
max(loglik)                 # maximum loglikelihood over all values of pb
pb[loglik == max(loglik)]   # MLE of pb
mle_pb_m1_nlsy <- pb[loglik == max(loglik)]
max_logL_m1_nlsy <- max(loglik)

# Create ggplot of likelihood and log-likelihood functions
model1grid <- data.frame(pb = pb, lik1 = lik, loglik1 = loglik)
ggplot(data = model1grid, aes(x = pb, y = lik1)) +
  geom_line() +
  labs(x = "possible values of pb", y = "Likelihood")
ggplot(data = model1grid, aes(x = pb, y = loglik1)) +
  geom_line() +
  labs(x = "possible values of pb", y = "log Likelihood")
model1grid %>%
  filter(loglik1 > (-7500)) %>%
  ggplot(aes(x = pb, y = loglik1)) +
    geom_line() +
    labs(x = "possible values of pb with loglik above -7500", 
         y = "log Likelihood")

```

### Model 2: Sex Conditional Model (small 3 famly data set)

Assumes probability of having a boy depends on whether you've had boys previously

```{r}
# Find MLEs with 3-dimensional grid search
pbb <- seq(0, 1, length = 101)
pbg <- seq(0, 1, length = 101)
pbn <- seq(0, 1, length = 101)
model2_grid <- expand.grid(pbb = pbb, pbg = pbg, pbn = pbn)

lik <- model2_grid$pbn^1 * (1 - model2_grid$pbn)^3 * model2_grid$pbb^1 * 
  (1 - model2_grid$pbb)^1 * model2_grid$pbg^1 * (1 - model2_grid$pbg)^1
loglik <- 1 * log(model2_grid$pbn) + 3 * log(1 - model2_grid$pbn) + 
  1 * log(model2_grid$pbb) + 1 * log(1 - model2_grid$pbb) + 
  1 * log(model2_grid$pbg) + 1 * log(1 - model2_grid$pbg)

# Print results
max(lik)        # maximum likelihood over all combos of pbb, pbg, pbn
max(loglik)     # maximum loglikelihood over all combos of pbb, pbg, pbn

model2_grid$pbb[loglik == max(loglik)]   # MLE of pbb
model2_grid$pbg[loglik == max(loglik)]   # MLE of pbg
model2_grid$pbn[loglik == max(loglik)]   # MLE of pbn

# Store results
mle_pbb_m2_small <- model2_grid$pbb[loglik == max(loglik)]   # MLE of pbb
mle_pbg_m2_small <- model2_grid$pbg[loglik == max(loglik)]   # MLE of pbg
mle_pbn_m2_small <- model2_grid$pbn[loglik == max(loglik)]   # MLE of pbn

max_L_m2_small <- max(lik)
max_logL_m2_small <- max(loglik)
```

### Model comparisons - Model 1 vs. Model 2

```{r}
lrt <- 2 * (max_logL_m2_small - max_logL_m1_small)   
lrt                       # likelihood ratio test statistic
1 - pchisq(lrt, df = 2)   # p-value for testing Ho: no diff between Models 1&2

# AIC and BIC values for Models 1 and 2
aic1 <- -2 * max_logL_m1_small + 2 * 1
aic1
bic1 <- -2 * max_logL_m1_small + log(8) * 1
bic1
aic2 <- -2 * max_logL_m2_small + 2 * 3
aic2
bic2 <- -2 * max_logL_m2_small + log(8) * 3
bic2
```
