---
title: "Homework 7"
subtitle: "Ch 7: Correlated Data"
---

`r if (knitr:::is_html_output()) '\\newcommand{\\E}{\\operatorname{E}}'`
`r if (knitr:::is_html_output()) '\\newcommand{\\SD}{\\operatorname{SD}}'`
`r if (knitr:::is_html_output()) '\\newcommand{\\var}{\\operatorname{Var}}'`


## Setup

Each of your assignments will begin with the following steps.

-   Going to our RStudio Server at <http://turing.cornellcollege.edu:8787/>

-   Creating a new *R project*, inside your homework folder on the server, and giving it a sensible name such as *homework_6* and having that project in the course folder you created. 

-   Create a new quarto document and give it a sensible name such as *hw6*.

-   In the `YAML` add the following (add what you don't have). The embed-resources component will make your final rendered `html` self-contained.

    ```{r}
#| label: yaml_example
#| eval: false
---
title: "Document title"
author: "my name"
format:
  html:
    embed-resources: true
---
    ```

## Instructions

Be sure to include the relevant R code as well as full sentences answering each of the questions (i.e. if I ask for the average, you can output the answer in R but **also** write a full sentence with the answer). Be sure to frequently save your files!

Data for the homework will be in the STA363_inst_files -> data folder.

## Exercises

All problems are from {{< var course.text >}} Abbreviated BMLR. 

Use the numbering on the left. The codes are for instructor use (Ex: C1).

## Part 1: Correlated Data

### Exercise 1

1. (C1) __Examples with correlated data.__ For each of the following studies: 
    i. Identify the most basic observational units
    ii. Identify the grouping units (could be multiple levels of grouping)
    iii. State the response(s) measured and variable type (normal, binary, Poisson, etc.)
    iv. Write a sentence describing the within-group correlation.
    v. Identify fixed and random effects

a. *Epilepsy study.*  Researchers conducted a randomized controlled study where patients were randomly assigned to either an anti-epileptic drug or a placebo.  For each patient, the number of seizures at baseline was measured over a 2-week period.  For four consecutive visits the number of seizures were determined over the past 2-week period. Patient age and sex along with visit number were recorded.

b. *Prairie restoration.*  Researchers at a small Midwestern college decided to experimentally explore the underlying causes of variation in soil reconstruction projects in order to make future projects more effective. Introductory ecology classes were organized to collect weekly data on plants in pots containing soil samples. Data will be examined to compare:
    - germination and growth of two species of prairie plants—--leadplants (*Amorpha canescens*) and coneflowers (*Ratibida pinnata*).
    - soil from a cultivated (agricultural) field, a natural prairie, and a restored (reconstructed) prairie.
    - the effect of sterilization, since half of the sampled soil was sterilized to determine if rhizosphere differences were responsible for the observed variation.
    
c. *Radon in Minnesota.*  Radon is a carcinogen – a naturally occurring radioactive gas whose decay products are also radioactive – known to cause lung cancer in high concentrations. The EPA sampled more than 80,000 homes across the U.S.  Each house came from a randomly selected county and measurements were made on each level of each home.  Uranium measurements at the county level were included to improve the radon estimates.
    
# Submission

When you are finished with your homework, be sure to Render the final document. Once rendered, you can download your file by:

-   Finding the .html file in your File pane (on the bottom right of the screen)
-   Click the check box next to the file
-   Click the blue gear above and then click "Export" to download
-   Submit your final html document to the respective assignment on [Moodle]({{< var course.moodle >}})



